#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
nohup node $OPENSHIFT_REPO_DIR/weinre.server/weinre --httpPort 8080 --boundHost $OPENSHIFT_INTERNAL_IP > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &
