#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to

PORT=${OPENSHIFT_DIY_PORT:-8080}
LOG=$OPENSHIFT_DIY_LOG_DIR/server.log

nohup node $OPENSHIFT_REPO_DIR/weinre.server/weinre --httpPort $PORT --boundHost $OPENSHIFT_DIY_IP > $LOG 2>&1 &
